version: 2.1

jobs:
  standards:
    docker:
      - image: circleci/php:7.3.3-stretch-node-browsers
    steps:
      - checkout
      - install-dependencies
      - run: composer phpcs
      - run: npm run lint:css
      - run: npm run lint:js

  bundle:
    docker:
      - image: circleci/node:12.12.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run zip
      - run: mkdir /tmp/artifacts
      - run: mv ./*.zip /tmp/artifacts/.
      - store_artifacts:
          path: /tmp/artifacts/

commands:
  install-dependencies:
    description: "Install development dependencies."
    steps:
      - run: composer install
      - run: npm ci
workflows:
  version: 2
  check-standards:
    jobs:
      - standards
      - bundle:
          filters:
            tags:
              only: /.*/
